//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.22 at 09:09:36 PM CET 
//


package common.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Citizens">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Citizen" type="{}PersonType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DeregisteredCars">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Car" type="{}CarType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "citizens",
    "deregisteredCars"
})
@XmlRootElement(name = "CarsInformation")
public class CarsInformation {

    @XmlElement(name = "Citizens", required = true)
    protected CarsInformation.Citizens citizens;
    @XmlElement(name = "DeregisteredCars", required = true)
    protected CarsInformation.DeregisteredCars deregisteredCars;

    /**
     * Gets the value of the citizens property.
     * 
     * @return
     *     possible object is
     *     {@link CarsInformation.Citizens }
     *     
     */
    public CarsInformation.Citizens getCitizens() {
        return citizens;
    }

    /**
     * Sets the value of the citizens property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarsInformation.Citizens }
     *     
     */
    public void setCitizens(CarsInformation.Citizens value) {
        this.citizens = value;
    }

    /**
     * Gets the value of the deregisteredCars property.
     * 
     * @return
     *     possible object is
     *     {@link CarsInformation.DeregisteredCars }
     *     
     */
    public CarsInformation.DeregisteredCars getDeregisteredCars() {
        return deregisteredCars;
    }

    /**
     * Sets the value of the deregisteredCars property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarsInformation.DeregisteredCars }
     *     
     */
    public void setDeregisteredCars(CarsInformation.DeregisteredCars value) {
        this.deregisteredCars = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Citizen" type="{}PersonType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "citizen"
    })
    public static class Citizens {

        @XmlElement(name = "Citizen", required = true)
        protected PersonType citizen;

        /**
         * Gets the value of the citizen property.
         * 
         * @return
         *     possible object is
         *     {@link PersonType }
         *     
         */
        public PersonType getCitizen() {
            return citizen;
        }

        /**
         * Sets the value of the citizen property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonType }
         *     
         */
        public void setCitizen(PersonType value) {
            this.citizen = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Car" type="{}CarType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "car"
    })
    public static class DeregisteredCars {

        @XmlElement(name = "Car", required = true)
        protected CarType car;

        /**
         * Gets the value of the car property.
         * 
         * @return
         *     possible object is
         *     {@link CarType }
         *     
         */
        public CarType getCar() {
            return car;
        }

        /**
         * Sets the value of the car property.
         * 
         * @param value
         *     allowed object is
         *     {@link CarType }
         *     
         */
        public void setCar(CarType value) {
            this.car = value;
        }

    }

}
